services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5433:5432"

  app:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=authdb
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always  
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    working_dir: /app 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
